### ISSUE TITLE
Feature: Allow for full path match in find.

### ISSUE THREAD

**Issue by svyotov** [cytopia/docker-jsonlint#14]
https://github.com/cytopia/docker-jsonlint/blob/5d845116dccca8421711127181543660b44ba96c/data/docker-entrypoint.sh#L138

`-name` can be replaced with `-path` or `-wholepath` without loosing backwards compatibility as far as I am aware, while allowing to have paths in the regex.

**Comment by cytopia** [comment]
Isn't that something you would be doing with the mount option of docker instead?
```
docker run --rm -v <YOUR_PATH_HERE>:/data cytopia/jsonlint  ...
```

**Comment by cytopia** [comment]
@svyotov additionally you can specify paths via the glob pattern. See here: https://github.com/cytopia/docker-jsonlint#check-all-json-files-and-ignore-terraform-directories
