### ISSUE TITLE
No longer appears to be beign built regularly

### ISSUE THREAD

**Issue by dannystaple** [cytopia/docker-jsonlint#15]
The readme suggests this builds nightly, however, looking at the tags at https://hub.docker.com/r/cytopia/jsonlint/tags, this hasn't been built for a year.

**Comment by cytopia** [comment]
@dannystaple thanks for the reminder. Will need to migrate this away from Travis to GitHub actions. Should be done shortly and will let you know once the PR is up.

**Comment by cytopia** [comment]
https://github.com/cytopia/docker-jsonlint/pull/16
